name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get_cppcheck
        run:  sudo apt-get install -y libmath-libm-perl 
      - name: code quality
        run: make analysis-c-3_Imolementation
        
      - name: Cppcheck code
        run: cppcheck 
