name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install math library
        run:  sudo apt-get install -y libmath-libm-perl 
      - name: Install cppcheck
        run: sudo apt-get -y install cppcheck
        
      - name: Cppcheck code
        run: cppcheck 
